import os
import sys
import joblib
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Add src to python path to import configuration
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from config import config

class TransactionPreprocessor:
    """
    Fits and applies transformation pipelines for categorical and numerical features.
    Saves fit objects for reproducible offline and online preprocessing.
    """
    def __init__(self):
        self.scaler = StandardScaler()
        self.encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
        
        # Define features lists based on dataset structure
        self.numerical_cols = [
            "transaction_amount", 
            "account_age_days", 
            "customer_age", 
            "average_transaction_amount", 
            "transactions_last_24h", 
            "failed_transactions_last_24h", 
            "distance_from_home", 
            "ip_risk_score", 
            "device_trust_score", 
            "merchant_risk_score", 
            "hour_of_day", 
            "day_of_week"
        ]
        
        self.categorical_cols = [
            "merchant_category", 
            "merchant_country", 
            "customer_country", 
            "payment_method", 
            "transaction_type", 
            "device_type", 
            "operating_system", 
            "browser", 
            "customer_gender"
        ]
        
        self.binary_cols = [
            "previous_fraud_history", 
            "card_present", 
            "international_transaction", 
            "is_weekend"
        ]
        
        self.feature_order = None

    def fit(self, df: pd.DataFrame):
        """
        Fits scaler on numerical features and encoder on categorical features.
        """
        print("Fitting preprocessing pipelines...")
        self.scaler.fit(df[self.numerical_cols])
        self.encoder.fit(df[self.categorical_cols])
        
        # Save categorical column names generated by OHE
        encoded_cat_names = self.encoder.get_feature_names_out(self.categorical_cols).tolist()
        self.feature_order = self.numerical_cols + encoded_cat_names + self.binary_cols
        
    def transform(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Transforms numerical and categorical columns, retaining binary features.
        """
        # Copy to avoid side-effects
        df_copy = df.copy()
        
        # Scale numerical features
        scaled_numerical = self.scaler.transform(df_copy[self.numerical_cols])
        df_scaled_num = pd.DataFrame(scaled_numerical, columns=self.numerical_cols, index=df_copy.index)
        
        # Encode categorical features
        encoded_categorical = self.encoder.transform(df_copy[self.categorical_cols])
        encoded_cat_names = self.encoder.get_feature_names_out(self.categorical_cols)
        df_encoded_cat = pd.DataFrame(encoded_categorical, columns=encoded_cat_names, index=df_copy.index)
        
        # Concatenate numerical, encoded categorical, and binary columns
        df_binary = df_copy[self.binary_cols].reset_index(drop=True)
        df_processed = pd.concat([df_scaled_num.reset_index(drop=True), 
                                  df_encoded_cat.reset_index(drop=True), 
                                  df_binary], axis=1)
        
        # Reorder to keep schema identical
        if self.feature_order:
            df_processed = df_processed[self.feature_order]
            
        return df_processed

    def save(self, scaler_path: str = config.SCALER_PATH, encoders_path: str = config.ENCODERS_PATH):
        """
        Saves scaler and encoder configurations.
        """
        joblib.dump(self.scaler, scaler_path)
        # Store encoder and feature names mapping
        encoder_payload = {
            "encoder": self.encoder,
            "feature_order": self.feature_order,
            "numerical_cols": self.numerical_cols,
            "categorical_cols": self.categorical_cols,
            "binary_cols": self.binary_cols
        }
        joblib.dump(encoder_payload, encoders_path)
        print(f"Preprocessor objects saved successfully to {scaler_path} and {encoders_path}")

def run_preprocessing_pipeline():
    """
    Executes train/test splitting and processes data for machine learning.
    """
    print(f"Loading raw data from: {config.RAW_DATA_PATH}...")
    if not os.path.exists(config.RAW_DATA_PATH):
        print("Raw transaction data not found! Please run the generator first.")
        return
        
    df = pd.read_csv(config.RAW_DATA_PATH)
    
    # Split features and target
    X = df.drop(columns=["transaction_id", "customer_id", "merchant_name", "transaction_time", "fraud"])
    y = df["fraud"]
    
    # Perform train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=config.TEST_SIZE, random_state=config.RANDOM_SEED, stratify=y
    )
    
    # Initialize and fit pipeline
    preprocessor = TransactionPreprocessor()
    preprocessor.fit(X_train)
    
    # Transform
    X_train_processed = preprocessor.transform(X_train)
    X_test_processed = preprocessor.transform(X_test)
    
    # Save preprocessors
    preprocessor.save()
    
    # Add target column back for storage
    train_processed = X_train_processed.copy()
    train_processed["fraud"] = y_train.values
    
    test_processed = X_test_processed.copy()
    test_processed["fraud"] = y_test.values
    
    # Save split data
    train_processed.to_csv(config.PROCESSED_TRAIN_PATH, index=False)
    test_processed.to_csv(config.PROCESSED_TEST_PATH, index=False)
    
    print(f"Preprocessing completed!")
    print(f"Processed training set shape: {train_processed.shape}")
    print(f"Processed testing set shape: {test_processed.shape}")

if __name__ == "__main__":
    run_preprocessing_pipeline()
